### ISSUE TITLE
toWIF failed in browser?

### ISSUE THREAD

**Issue by guotie** [bitcoinjs/bip32#86]
next.js 14.1

```
Uncaught TypeError: Cannot read properties of undefined (reading 'call')
    at Hash.CipherBase (index.js:7:15)
    at new Hash (browser.js:8:10)
    at createHash (browser.js:23:12)
    at sha256x2 (index.js:6:15)
    at Object.encode (base.js:7:24)
    at Object.encode (index.js:38:55)
    at BIP32.toWIF (bip32.js:151:24)
    at generateBTCAddress (addr.ts:90:35)
    at generateAddress (BTCAddress.tsx:11:36)

```

**Comment by housenkui** [comment]
me too. who can fix the bug?

**Comment by junderw** [comment]
4.0.0 no longer uses create-hash at all.
